### ISSUE TITLE
command/query: see statistics on a user

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#10]
**command/query:** see statistics on a user. We have wallet address and label access control details. We should eventually include repo/org/global XP as well, and possibly dollars earned if our ledger works.

[See source code](https://github.com/ubiquity/ubiquibot/blob/579c447ce23397d8947e2f3f2a5e665f1c60fedf/src/handlers/comment/handlers/query.ts)

[See related repository](https://github.com/ubiquibot/command-query-user)

**Comment by BeanieMen** [comment]
.

**Comment by gentlementlegen** [comment]
@0x4007 I think we gonna have to fix that 😅

**Comment by BeanieMen** [comment]
H
