### ISSUE TITLE
Plugin starter pack

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugins-wishlist#13]
Package all of the common and required parts needed to build a plugin and host a template repo 

- All common shared types
- All Supabase adapters
- Libs such as `@ubiquity/configuration`, `@ubiquity/logger`?,  ...etc
- Basic ts plugin entry w/ Context setup
- Basic workflow setup
- Maybe some of the most used utility/helper functions because there are a few variations of these functions across different features all doing the same thing
- Strip out unused scaffolding from https://github.com/ubiquity/ts-template (cypress, esbuild etc) using that as the foundation
- Include steps on how to test a plugin locally when in development

<hr/>

Improves DX, streamlines development and with any breaking changes to how plugins are developed they can be kept up-to date in the template's readme.

- I have based my plugins so far on the structure of [Assistive Pricing](https://github.com/ubiquibot/assistive-pricing/) 
- [Start/Stop](https://github.com/ubq-testing/start-stop-module) is closer to what the template should look like but should be more broad-strokes that way developers can remove whatever pieces they don't need (i.e adapters etc)

##### time estimate: < 1-2 hrs

**Comment by Keyrxng** [comment]
- https://github.com/Keyrxng/ubiquibot-plugin-template

very basic rn but gets the core stuff needed to get up and running quickly

adding specific utils etc will be easier once all of V1/I have more exp porting/creating plugins. It started to quickly bloat so I kept it thin for now

**Comment by gentlementlegen** [comment]
@Keyrxng Please move the work to the following repository
https://github.com/ubiquibot/plugin-template

Also side note, the template should include the Worker setup as well I suppose.

**Comment by gentlementlegen** [comment]
@Keyrxng How is this coming along? Would be neat to have it for future plugins.

**Comment by Keyrxng** [comment]
@gentlementlegen I'll get on it, I was holding off because of https://github.com/ubiquibot/plugins-wishlist/issues/9 not moving along thinking that the reason is because the direction for workers wasn't completely decided on.

**Comment by gentlementlegen** [comment]
We have https://github.com/ubiquibot/command-query-user which was set up as a worker. I think the template should contain both setups, since they can coexist with no issue.

**Comment by Keyrxng** [comment]
@gentlementlegen can you add an empty readme to the repo so I can fork it easier please bud

**Comment by gentlementlegen** [comment]
@Keyrxng Good to go

**Comment by Keyrxng** [comment]
@0x4007 @gentlementlegen, shouldn't it be the case that if someone creates the issue and then also completes it then they should receive whichever reward is the highest between the task price and task creation reward + comments?

**Comment by gentlementlegen** [comment]
@Keyrxng Should be fixed now. The reason why you got unassigned is most likely because you were considered as inactive, but the bot does not update a user status without having any sort of activity on the task.

**Comment by Keyrxng** [comment]
> ### [ [ 7.9 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI3OTAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNDMxMzAyMDU4MzAwMjYwOTIxOTQ0Nzk3Njk2MDE3MTM1NzIwODYyNjk2MTkyNTAzOTYyMDExMTg4NDM1MjQ3MDcwMTIyMTM1OTA4NzIiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDBmQzFiOTA5YmE5MjY1QTg0NmI4MkNGNENFMzUyZmMzZTdFZUIyRUQiLCJyZXF1ZXN0ZWRBbW91bnQiOiI3OTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHg0NENhMTVEYjEwMWZEMWMxOTQ0NjdEYjZBRjBjNjdDNkJiRjRBQjUxIiwic2lnbmF0dXJlIjoiMHhjOTFhODQ3Y2FmMDhjZmZlODMwMzQ3MjIxODU4YWVkNzMxZTIxZGJjMTk2MjE2OGM2NzE5OGE4OWRiMzA0YTczMGUwN2I3NDdkZjY3OWYzNzM3ZjhkM2QzMTA3ZTk1NTkyMmZjNDZkMTAwNDdlZTllYjczMGE1OWIzNzcyZTkwNjFjIiwibmV0d29ya0lkIjoxMDB9XQ%3D%3D)
> ###### @gentlementlegen
> ### [ [ 271.2 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyNzEyMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIzMzE0NDg4ODgyMzA4MDI2MDE4NzkyNDgzMjc1MTY2MTc1NTg5NDM4MzgzMzMwMzQ3MzYyMDUyNTAxNTQzMzk1NDcyNDUwNjY2NTg0IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhBZTVEMUYxOTIwMTNkYjg4OWIxZTIxMTVBMzcwYUIxMzNmMzU5NzY1IiwicmVxdWVzdGVkQW1vdW50IjoiMjcxMjAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHg0NENhMTVEYjEwMWZEMWMxOTQ0NjdEYjZBRjBjNjdDNkJiRjRBQjUxIiwic2lnbmF0dXJlIjoiMHg0Zjg3ZDYyZmUzODk0MzBiYTdmM2Q1ZGY4YTg3N2M3ZDQxZmM3OWJhZDhlMDFhNDk2NjlkMmY3MGQwZDg1NTg1NDExOTcxY2IxOTBlZTY3Zjg3NGE0ZjNlMGViZWEyMDUxN2UxZTUxMGQzOGQ0MTYwNTdiNjFmYjFiYTI0MjJlODFjIiwibmV0d29ya0lkIjoxMDB9XQ%3D%3D)
> ###### @Keyrxng

Hotdamn, I expected a difference of ~$80. I had to claim the permit this morning for $87 as I needed it for food (one day I'll be poverty free 🤣). 

@0x4007 would you be able to manual the difference this one time and I will not do this again, I'd of been okay losing ~$80 if there was no resolve possible but not ~$190 that's brutal af.

<hr/>

I hear you regarding the bot ejection @gentlementlegen, it was just a thought, it could be a potential new plugin even?

**Comment by gentlementlegen** [comment]
@Keyrxng Yes, working on it: https://github.com/ubiquibot/plugins-wishlist/issues/7

**Comment by Keyrxng** [comment]
@gentlementlegen I was meaning the specific feature of re-assigning the author of the incoming merge if they are currently not assigned to the assignee and the assignee is null?

e.g. if they have been removed by wildcard/unassign previously but are the rightful PR author when the PR is finally merged. 
e.g. alternatively, if the assignee is not null. You resolved an issue not too long ago which jordan was assigned to, the merged PR you authored and subsequently you received the payout albeit manually processed after the merge. This new plugin could handle these scenarios and remove the need for reviewers/hunters to double check before generating the permit?

<hr/>

If a user has been removed by wildcard then they'll have had the XP/Karma reductions so being unassigned and then it being merged 1 or 2 weeks later (through either their own fault or due to slow review) has no negative effects.

Other than, an issue appears to be open and workable when in reality it isn't so it circumvents that a bit.

I'm just thinking QOL would be improved

**Comment by gentlementlegen** [comment]
This is a valid point, but I think this scenario is induced by the unassign logic not being accurate. If a user gets a reminder and a notification when they get unassigned, they would have reassigned themselves before the PR was opened / merged. In your case you got unassigned the same second the PR was closed which resulted in this problem. Hopefully this scenario would not be common on the v2, but I'll keep it in mind.

**Comment by 0x4007** [comment]
@Keyrxng I sent 150 for the task reward https://gnosisscan.io/tx/0x2d809e7abe91a4751da60483b3c95c19b398a1167872286474dee9ed0110117b
