### ISSUE TITLE
Task Gamification

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#14]
To incentivize people to commit more into being active within the organization, a gamification going through an "xp" system could be a great addition. This would reflect for each user its level of commitment doing chores of any kind related to the progress of the project. By this I think of reviews, comment, pull-requests, issue specification, or any sort of activity that implied time committed from a user.

Few possible features that could be implemented to influence the xp / reward value:
- a global leaderboard (weekly / all time...)
- leagues for users
- [a streak counter](https://github.com/ubiquibot/plugins-wishlist/issues/1)
- a multiplier, based on the status of the user, or on its league
- league decay over time
- penalties on missed deadlines, comment reported by users
- a "heart" system to allow preserving streaks

The final purpose of these features are to make the user eager to collaborate, and engage in diverse activities within the repo (not only coding but also reviewing, commenting, researching an so on).

**Comment by 0x4007** [comment]
Yes but I think that we should only concern ourselves with storing the XP metadata (timestamp, amount) in the database and each application built on top of this can read the raw data and display it differently (i.e. "league decay over time", "streak counter")
