### ISSUE TITLE
/help command

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#17]
In the v1 of the bot, the `/help` would help the user to see all available commands with the Bot. The v2 should also offer a similar capability.

It is trickier because now each plugin is capable of handling its own commands. We should find a way to collect all of them and output them in a table, looking like

| command | description | example
-------|----|---
| /help | Outputs help |  ```/help``` |

Few possible ways:
- implement a unified way, maybe through an endpoint, to collect commands
- rely on the `command` section of the configuration file

**Comment by 0x4007** [comment]
I think that it should be built into the kernel, and it should parse the active config and generate the available commands.

**Comment by gentlementlegen** [comment]
@0x4007 I believe so too. Still means the kernel should have a way to query each plugin to know their available commands. Only way I see to avoid querying them is directly reading the `command` inside the configuration itself. But since it is not mandatory, we could potentially have missing information there.

**Comment by gentlementlegen** [comment]
We might want to remove `@user` or escape it in the example since it actually tags a real user here.

**Comment by 0x4007** [comment]
> But since it is not mandatory, we could potentially have missing information there.

This help menu is just for slash commands. To register it as a slash command, it should be mandatory to define in the config. 

The help menu is not intended to explain every webhook event result. 

> We might want to remove @user or escape it in the example since it actually tags a real user here.

They know what they were doing when they created the username. It's fine.

**Comment by gentlementlegen** [comment]
@0x4007 I believe for now I will read the command and description from the configuration file and display it in a similar fashion as we have now like https://github.com/ubiquibot/plugins-wishlist/issues/17#issuecomment-2167215039
What would have been cool if plugins would take care of themselves about the help output, is to have help for sub-commands like
`/help assign` that would show a more elaborate description about that specific command.

**Comment by gentlementlegen** [comment]
@0x4007 @whilefoo I had created a plugin repo for this at first, but it appears to me that this one might belong to the kernel because we do not send the whole configuration to invoked plugins afaik (and might not make much sense to do so anyway). 

Would that be fine or do you have suggestions?

**Comment by 0x4007** [comment]
Yes I am leaning towards this being in the kernel as well, unless its viable to isolate into its own codebase. 

Ideally we have it on a Cloudflare Worker in its own plugin, and then perhaps have it set in the kernel to call it either via hard coding or an environment variable of "built-ins"

**Comment by whilefoo** [comment]
I think having it in the kernel seems most logical since it already has the config and it's not so much code
