### ISSUE TITLE
Post tasks to the DevPool

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#18]
One of the main capabilities of the bot is to be able to post tasks that have an assigned Time, Priority and Reward to the main repo containing all the DevPool tasks. This should also be implemented with the new Bot.

Example:
https://github.com/ubiquity/devpool-directory/issues/1195

**Comment by 0x4007** [comment]
We have a whitelist system using [opt.json](https://github.com/ubiquity/devpool-directory/blob/development/opt.json)

If I am understanding your proposal correctly, this should be closed as unplanned.

**Comment by gentlementlegen** [comment]
Shouldn't the bot add newly created Issues to the DevPool repository so it is displayed in https://work.ubq.fi/ ?

**Comment by 0x4007** [comment]
Only whitelisted projects. I suspect there will be a lot of low quality tasks produced that will detract from the early DevPool experience for developers.
