### ISSUE TITLE
/wallet command

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#23]
Users should be able to set / update their associated wallet that will be used to collect their rewards.

Tasks to be carried out:
- implement a `/wallet` command that allows to set the user's wallet
- be able to updated that wallet
- be able to query the current user's wallet

[Code reference](https://github.com/ubiquity/ubiquibot/blob/7d3e75cd1ea94bff73998ae4bcce1cc0f3e15ab7/src/handlers/comment/handlers/wallet.ts)

[Related repository](https://github.com/ubiquibot/command-wallet)

**Comment by 0x4007** [comment]
I'm surprised this wasn't on the original roll out of plugins? This is an essential feature

**Comment by 0x4007** [comment]
Interesting that it didn't credit my review comments.

**Comment by gentlementlegen** [comment]
Neither were mine not @rndquu 
I think the bot v2 does, but somehow it didn't run.
