### ISSUE TITLE
`issues_comment.created` vector embeddings

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/plugins-wishlist#32]
- This allows the bot to learn and understand from all of the comments posted on GitHub. 
- This serves as the foundation of its intelligence related to an organization or repository's initiatives. 
- We should also update based on `issues_comment.edited`
- We should also save the issue specification. 
- Related https://github.com/ubiquibot/comment-incentives/issues/9

This task serves as the initial setup but once the repository is made we can migrate those old issues. The old issues will also probably need to be updated with more modern technologies. Generally the same strategy on the approach will be used still.

**Comment by 0x4007** [comment]
@sshivaditya2019 supabase has first class support for vector embeddings which might be easier for you to get started with.

**Comment by sshivaditya2019** [comment]
@0x4007 Could you provide additional details on this issue?

So, all the existing comments will be stored in vector store. Ann when comments are edited they have to updated in the vector store. Is that right ?

**Comment by 0x4007** [comment]
I would make the row ID the comment id. You can also store the issue specification by storing the issue id (not issue number of the repo, but id which is a large number)

**Comment by 0x4007** [comment]
@Keyrxng  do you have any resources for how @sshivaditya2019 can get started on building a plugin?

**Comment by sshivaditya2019** [comment]
So, the issues (along with spec), and the comments would be stored in a db (Separate Tables), but we need embeddings only for the comments. Is that right ?

**Comment by Keyrxng** [comment]
1. https://github.com/ubiquibot/plugin-template - It contains a small hello-world example and the readme has various links and tips.
2. Use the most recent plugins for reference such as: [`command-start-stop`](https://github.com/ubiquibot/command-start-stop), [`automated-merging`](https://github.com/ubiquibot/automated-merging), [`command-wallet`](https://github.com/ubiquibot/command-wallet)
3. If you are not already familiar with the kernel and the prerequisites of plugin building head [here](https://github.com/ubiquity/ubiquibot-kernel)

---

@0x4007 Maybe it's time for an early version of official docs? Covering things like secret passing and description of the main components, best practices etc? There is the videos that gitcoindev made I will find those and link them

**Comment by 0x4007** [comment]
> So, the issues (along with spec), and the comments would be stored in a db (Separate Tables), but we need embeddings only for the comments. Is that right ? 

Just issue body and comments. Same table. IDs shouldn't collide.

**Comment by 0x4007** [comment]
> Also could you create a repo for this plugin so that @sshivaditya2019 can fork the repo for an easy PR?

I'm not on my computer so they can fork from you for now

**Comment by Keyrxng** [comment]
@sshivaditya2019 you can fork this repo

- https://github.com/ubiquibot/issue-comment-embeddings

@0x4007 I have a poor track record with naming plugins I think lmao it probs could have a better name

**Comment by 0x4007** [comment]
@Keyrxng i think this was eligible for the additional Dora hacks incentive. Would you be able to handle this?

**Comment by Keyrxng** [comment]
@sshivaditya2019 If you can enter a submission to dorahacks with a link to this issue and your github username please I can process it

**Comment by 0x4007** [comment]
I just realized the original plan was to use cloudflare free embeddings. We can make this cost optimization later but @sshivaditya2019 is there any specific reason why you must use open ai embeddings?

**Comment by sshivaditya2019** [comment]
> I just realized the [original plan](https://github.com/ubiquibot/comment-incentives/issues/9) was to use cloudflare free embeddings. We can make this cost optimization later but @sshivaditya2019 is there any specific reason why you must use open ai embeddings? 

Open ai embeddings are better than better for designing future AI applications using the data. As far as I know Cloudflare embeddings are restricted to the paid plan.

**Comment by sshivaditya2019** [comment]
@Keyrxng have created the submission on Dora hacks.

**Comment by 0x4007** [comment]
> Open ai embeddings are better for designing future AI applications using the data.

Why

**Comment by sshivaditya2019** [comment]
> > Open ai embeddings are better for designing future AI applications using the data.
> 
> Why

One, [leaderboard](https://huggingface.co/spaces/mteb/leaderboard), wise `[text-embedding-3-large](https://openai.com/blog/new-embedding-models-and-api-updates)` is better than `[bge-large-en-v1.5](https://developers.cloudflare.com/workers-ai/models/bge-large-en-v1.5)`. Two, from what I have used Context retrieval is better in `Open AI Model`.

**Comment by Keyrxng** [comment]
@sshivaditya2019 

https://polygonscan.com/tx/0x93d290e768a53f4a14bac7ccf171dba61b7a2081d69a702213b665613abc9bfb

**Comment by gentlementlegen** [comment]
I created the DB and updated secrets accordingly. The RLS on the DB has not been set up inside the migrations however, opened a ticket for that.

**Comment by 0x4007** [comment]
> > > Open ai embeddings are better for designing future AI applications using the data.
> > 
> > 
> > Why
> 
> One, [leaderboard](https://huggingface.co/spaces/mteb/leaderboard), wise [text-embedding-3-large](https://openai.com/blog/new-embedding-models-and-api-updates) is better than [bge-large-en-v1.5](https://developers.cloudflare.com/workers-ai/models/bge-large-en-v1.5). Two, from what I have used Context retrieval is better in `Open AI Model`.

`bge-large-en-v1.5` is rank `30`. 

`text-embedding-3-large` is rank `309`

**Comment by sshivaditya2019** [comment]
> > > > Open ai embeddings are better for designing future AI applications using the data.
> > > 
> > > 
> > > Why
> > 
> > 
> > One, [leaderboard](https://huggingface.co/spaces/mteb/leaderboard), wise [text-embedding-3-large](https://openai.com/blog/new-embedding-models-and-api-updates) is better than [bge-large-en-v1.5](https://developers.cloudflare.com/workers-ai/models/bge-large-en-v1.5). Two, from what I have used Context retrieval is better in `Open AI Model`.
> 
> `bge-large-en-v1.5` is rank `30`.
> 
> `text-embedding-3-large` is rank `309`
> 
> We should be using the highest quality and cheapest models.

The leaderboard, does not have all components filled [text-embedding-3-large](https://openai.com/index/new-embedding-models-and-api-updates/) has a average MTEB average of 64.6 and [bge-large-en-v1.5](https://developers.cloudflare.com/workers-ai/models/bge-large-en-v1.5) has 64.23. If sort by retrieval score `text-embedding-3-large` should be better.

Also, `Cloudflare Worker AI` platform is not GA yet.

**Comment by 0x4007** [comment]
I filed [a new issue](https://github.com/ubiquibot/issue-comment-embeddings/issues/8) because I realize that you didn't save the issue bodies as we agreed. 

Please prioritize handling it @sshivaditya2019

**Comment by sshivaditya2019** [comment]
> I filed [a new issue](https://github.com/ubiquibot/issue-comment-embeddings/issues/8) because I realize that you didn't save the issue bodies as we agreed. 
> 
> Please prioritize handling it @sshivaditya2019 

As far as I know issuebodies are stored as per the schema. The issue text is stored in 'issuebody' column.

**Comment by 0x4007** [comment]
@Keyrxng set up their own database and ran this but couldn't find any issues saved

**Comment by sshivaditya2019** [comment]
> @Keyrxng set up their own database and ran this but couldn't find any issues saved

In [#8](https://github.com/ubiquibot/issue-comment-embeddings/issues/8), the image in the issue spec, has the issue bodies. Just to be clear by issue body you are referring to the issue's text body right ?

**Comment by 0x4007** [comment]
Sorry I meant that they need the ID of the issue and the issue body alone. You emphasized the schema on the comments and their IDs.
