### ISSUE TITLE
`/remindMe` slash command

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugins-wishlist#38]
Relates to https://github.com/ubiquity/recruiting/issues/11 (maybe)

Plugin Specification:

- It should allow a user to comment `/remindMe 2 weeks` or any form of NLP to that effect
- The plugin should use GitHub as the storage layer, preferably a simple JSON storage approach.
- It should run often enough that it can post hourly updates (if there are reminders to be fired)
- It's expected that the user would be tagged by the bot after but as close to the time as possible when the 'remind me' comment was created
- Once tagged, the reminder should be cleared from storage

Task Specification:

- All contributors must open a PR directly against the repo (TODO), do not use the `/start` command or manually assign.
- Any basic questions or help that you need, please don't be afraid comment on this issue. You will be rewarded for valid and impactful comments. Anything specific to your build should be included within your PR.
- Submissions will be reviewed after the deadline has passed. Any contributions beyond this deadline will result in disqualification from being selected as the winner

Reward Details:

- The submission which is decided to be the best will receive the reward via Replit, where the bounty for this task exists.
- The submission is not expected to be ready to merge into production but the PR which is closest to production-ready and follows similar patterns to those found in current production plugins would be in great standing.

**Comment by 0x4007** [comment]
It's a better investment to build something we need that requires storage, perhaps the XP system, if the intention is to create a task that as a side effect, yields the storage solution. 

There are other, superior tools that already exist for reminders, such as Google Calendar.

**Comment by Keyrxng** [comment]
> It's a better investment to build something we need that requires storage, such as the XP system, if the intention is to create a task that, as a side effect yields the storage solution.
> 
> There are other, superior tools that already exist for reminders, such as Google Calendar.

I think this task should remain open and I update the spec.

This is similar to the bots you find on twitter and reddit. It's not for something you'd need to go out of your way to open up google calendar and set a date to come back to

This is for off-the-cuff reminders to return to a particular issue/PR/discussion for whatever reason. A quick three word comment and it's done, you get your reminder when you asked for it. You see it's use in the wild very often so it's a small jump to say that it would be just as useful on GitHub as X etc.

Here is where you personally would have used this plugin [very recently](https://github.com/ubiquibot/command-start-stop/issues/6#issuecomment-2300643425) and I got the idea for it immediately after reading that comment the other day

**Comment by 0x4007** [comment]
> Here is where you personally would have used this plugin [very recently](https://github.com/ubiquibot/command-start-stop/issues/6#issuecomment-2300643425) and I got the idea for it immediately after reading that comment the other day

I get the reminder in the form of a notification when you mark it as complete.
