### ISSUE TITLE
Fact checker

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugins-wishlist#41]
It could be interesting to build a plugin which has web search and parsing capabilities that leverages AI to fact check a statement/comment.

For example:

user1: "The order of object keys is immutable and will never change between accesses"
user2: "/fact-check 'The order of object keys is immutable and will never change between accesses'"

The LLM would do as Google etc do. Pulls from multiple sources and creates a well-rounded unbiased comment based on the search results, linking to the relevant source for each excerpt.

The result should be posted in response to the slash command.

---

I think this might be better than just asking the LLM directly for it's answer. This would aim to prevent hallucinations and also provides the user with evidence of the fact by linking to sources.

**Comment by 0x4007** [comment]
I think that ask would already handle this quite well. I haven't had any problems with coding hallucinations since like gpt3.5. 

Even if you can make a strong case for why we need the latest information from the internet, isn't this basically the same as the perplexity task?

**Comment by Keyrxng** [comment]
> isn't this basically the same as the perplexity task?

Not really it only had the info it was trained on and what we fed to it. 

I thought it might be beneficial for it to be able to bring sources into the conversation as we often do during discussions ourselves but you are right hallucinations are less common with recent models

**Comment by 0x4007** [comment]
> Not really it only had the info it was trained on and what we fed to it.

Perplexity searches the internet and provides a summary of its findings. We have an old spec for it, and I'm pretty sure you made the prototype.
