### ISSUE TITLE
Automatic Responses

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugins-wishlist#42]
Related to https://github.com/ubiquity/devpool-directory-bounties/issues/36

This would be handy to have as a plugin which can be configured to automatically respond to comments on any repo task.

- it runs on `issue_comment.created`
- its config could be a Record of `repoName: custom response to use`

Primary use-case:

- Set up automatic replies for the `devpool-directory` repo whenever someone comments we automatically redirect them to the actual task. Despite it being in the task body I have fell for it and I have seen others fall for it too

Secondary use-case: 

- Agents: Once they are set up this plugin could likely be used to setup automatic replies to certain events or triggers

**Comment by 0x4007** [comment]
Agents should have their own logic to handle replies. 

I replied for the devpool directory problem in the issue. Basically I think this proposal doesn't make sense to proceed with.
