### ISSUE TITLE
wildcard/unassign: user activity watcher

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#7]
**wildcard/unassign:** we should create a plugin that checks certain conditions across every assigned task to determine if the assignee is still actively working on it. If not, give them a follow up. If they abandoned the task then unassign. Make sure to punish them by subtracting XP!

[See code reference](https://github.com/ubiquity/ubiquibot/tree/8aaf055c091cc3e7f2b42c9f1cf88f45b1d86d17/src/handlers/wildcard/unassign)

Related repository: https://github.com/ubiquibot/user-activity-watcher

**Comment by Keyrxng** [comment]
I can only really think of this plugin being an invoker of #9, wouldn't you agree?

If that is the case then #9 should not handle XP mods and this plugin should handle it? 

Alternatively, I've setup `/start` such that an invoker passes `directive === "start" | "stop"` and `xpAmount: number` and then #9 would handle the XP mods.

What's the best approach?

**Comment by gentlementlegen** [comment]
@Keyrxng I think this can be standalone because events would be sent from the kernel, so it doesn't matter if `start | stop` is invoked. I think this should be a watcher that updates the assignee status in the task according to reasons specified in the spec (time elapsed, activity, linked pr, commits and whatnot). Reached a certain point, a reminder is posted (maybe something like "are you still working on it? If not, unassign yourself before the bot does), and if nothing ensues simply unassign, and eventually apply XP penalties (still don't have any XP system so don't worry about it yet I guess).

**Comment by Keyrxng** [comment]
@jordan-ae is taking care of this task and yeah I understand. I made the relevant changes in `start/stop` thank you

**Comment by 0x4007** [comment]
> Quick question for the unassign user: what would be the conditions to disqualify exactly? I was reading the code but it's a bit unclear to me @gentlementlegen via Telegram

The purpose of this capability is to disqualify contributors that neglect to complete the task. A very common scenario is that a contributor will begin a task, and then give up, which means that the task is being blocked (other people will not work on it while it is already assigned.)

Before disqualification, the manager should ask for an update. If the contributor still has no updates, then the manager should disqualify the contributor by unassigning them, and ideally, not allowing them to reassign themselves (we could check in the `/start` command if the bot unassigned the contributor within the timeline.)

Any user activity that shows they are working on the task should be considered valid. Ideally we should be able to configure this. Definitely include watching commits. Possibly include watching comments on either the pull or the issue. I think these are the only two types of contributor events we should watch for.

**Comment by gentlementlegen** [comment]
So basically, whenever the user is detected as active, we push the deadline by the length of the task? E.g. it's a <1 Day task, each time activity is detected, we push the deadline by 1 day?

Also technically it is allowed on GitHub to have multiple users assigned on the same issue, should any activity of any user be counted to push the deadline? The old bot has some code but I suspect it never worked because it counts the same timers for everyone so either everyone is in the deadline or outside: https://github.com/ubiquity/ubiquibot/blob/8aaf055c091cc3e7f2b42c9f1cf88f45b1d86d17/src/handlers/wildcard/unassign/assign-event-found.ts#L20

**Comment by 0x4007** [comment]
> So basically, whenever the user is detected as active, we push the deadline by the length of the task? E.g. it's a <1 Day task, each time activity is detected, we push the deadline by 1 day?

Actually, this is configurable but we always did the following default settings. `3.5 days` for follow up, `7 days` for disqualify. I like these default settings as they allow for flexibility for holidays/weekends. The time estimate label is mostly used for pricing, but otherwise is not really leveraged in other aspects of our system. 

> Also technically it is allowed on GitHub to have multiple users assigned on the same issue, should any activity of any user be counted to push the deadline? The old bot has some code but I suspect it never worked because it counts the same timers for everyone so either everyone is in the deadline or outside: https://github.com/ubiquity/ubiquibot/blob/8aaf055c091cc3e7f2b42c9f1cf88f45b1d86d17/src/handlers/wildcard/unassign/assign-event-found.ts#L20

It seems like a detail I may have implemented, but in practice we never have multiple assignees to tasks. I think this could be useful for when companies/teams get involved in the future. I think it is more precise to manage on the per capita level, so we should consider each assignee individually as what appears to be implemented in your provided example.

**Comment by gentlementlegen** [comment]
In the provided example, it doesn't work because the calculation is the same for each user
```TypeScript
const assigneesWithinGracePeriod = assignees.filter(() => now - latestAssignEventTime < taskDisqualifyDuration);
```
All these values do not seem to be user based, but rather all the same for every user, just based on the latest event.

---

Okay so to sum it up:
- on user activity, add `3.5 days` before the next reminder (configurable)
- on user activity, add `7 days` before the complete disqualify (configurable)
- user based time tracking, considering that multiple users could be assigned to an issue

**Comment by gentlementlegen** [comment]
@0x4007 Might have had an idea on how to reduce load and trigger Actions only when we need to.

This reflection comes after testing the plugin, which fires like 5 builds a second due to the `'*'` being used.

We do not want to use Worker Alarms, and we do not want to use CRON. What about using a one time Workflow instead? For each job we want to schedule, we could create a dummy Workflow with the only purpose to trigger our main workflow with the desired values, that deletes itself upon completion.

Example, I want to send the reminder for a task tomorrow, I create a workflow with
```
on:
  schedule:
    - cron: '4 2 9 6 *'
```

which would fire tomorrow at 2am. Then this workflow deletes itself, and that's it, our main workflow is running on schedule.

What this fixes is:
- the crazy amount of workflows triggered on active repos
- the stale state of the reminders on inactive repos
- the need to listen to `*` for events

**Comment by 0x4007** [comment]
This is a novel approach I never did research on in the past so I need more information before I'm convinced. But it seems a bit heavy to write a workflow file somewhere regularly and then delete regularly.

**Comment by gentlementlegen** [comment]
@0x4007 Interesting that the issue didn't close despite being linked with https://github.com/ubiquibot/user-activity-watcher/pull/1 ; manually closing this.

**Comment by 0x4007** [comment]
I think the comment rewards are too high here. Especially with the occasional double counts

**Comment by gentlementlegen** [comment]
Didn't claim, so let me know.

**Comment by 0x4007** [comment]
Can claim I just need to adjust the settings I guess.

**Comment by gentlementlegen** [comment]
@0x4007 On this version the comments are evaluated like:

Issue | Comment | 5 | 114.2
-- | -- | -- | --
Issue | Comment | 5 | 0

I believe that the v2 currently would give the second row (0 reward for comments).
