### ISSUE TITLE
command/[start | stop]

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#9]
A user should be able to start or stop working on a task, by typing `/start` or `/stop` within a comment under an issue.

Stop this one will be especially useful to gracefully quit a task without losing XP. if somebody is disqualified through poor/non performance, then they will get negative XP.

[See code reference](https://github.com/ubiquity/ubiquibot/blob/ddd452ff20b254d05a81eea2ed17ac8c29ef557b/src/handlers/comment/handlers/stop.ts)

**Comment by jordan-ae** [comment]
@gentlementlegen so this start/stop should work exactly how the v1 Bot does currently?

**Comment by gentlementlegen** [comment]
@jordan-ae Correct, the goal is to reimplement the same functionalities but in a cleaner manner within separate modules.

**Comment by Keyrxng** [comment]
- https://github.com/ubq-testing/start-stop-module/issues/4 initial QA

Is a new repo going to be created for each plugin in the wishlist or are we to open PRs against this repo?

RFC @0x4007

**Comment by 0x4007** [comment]
Each plugin should be hosted on their own repositories.

**Comment by Keyrxng** [comment]
I thought that was the plan eventually, in the meantime think you could create one for `start/stop` for me please mate and I'll open a draft pr with this

**Comment by 0x4007** [comment]
I am not with my computer so @gentlementlegen maybe you can.

**Comment by Keyrxng** [comment]
- #7 this plugin handles the detection and the follow-up of the inactive hunter
- #9 this plugin is a slash command and basically the V1 unassign callback handler

Both have been mentioned to handle XP deductions although it should only be one.

<hr/>

I think it makes sense for #7 to have this plugin as part of it's `plugins: uses: with:` config, sending a negative XP amount and "stop" once it decides to kick & penalize the hunter. By invoking this plugin, any open PR would also be closed and XP is handled by only one.

Or I can remove the notion of XP handling in this and have it be _just_ a slash command plugin for `/start` and `/stop` not invoked by any other plugin. If #7 kicks the user and handles XP then it won't need to call into this which means a user can only use `/stop` while still still inside the deadline which shouldn't incur a negative XP impact anyway right?

**Comment by 0x4007** [comment]
Only wildcard unassign should deduct XP for inactivity. If a user gives up with /stop within the allocated timeframe it's fine. No punishment.

**Comment by Keyrxng** [comment]
PR ready for review once the repo is good to go.

I assume the org will just be `@ubiquibot-plugins/start-stop` for example? I've named it that temporarily

**Comment by gentlementlegen** [comment]
Apologies this slipped my mind. `start-stop` seems like a poor naming, maybe more something like `assignee-manager` since it helps with assigning users to tasks.

**Comment by Keyrxng** [comment]
Sure, maybe one of the following:

- assignment-manager
- bounty-assignment
- task-guardian
- task-entry-plugin
- task-assignment
- hunter-task-controller
- task-access-plugin
- user-bounty-controller

Whatever the repo gets called I'll change my code references

**Comment by gentlementlegen** [comment]
Related repository: https://github.com/ubiquity/command-start-stop

**Comment by 0x4007** [comment]
> Apologies this slipped my mind. `start-stop` seems like a poor naming, maybe more something like `assignee-manager` since it helps with assigning users to tasks.

`command-start-stop` is the best because it follows very clear standard syntax on how to name our repositories. 

- It is intended to operate as a slash command
- It has a start command
- It has a stop command

You can add a description under the repository description field that explains it is used for assignee management.

**Comment by 0x4007** [comment]
> @gentlementlegen is there a structure yet for the XP?
> 
> * If a user is automatically removed due to not meeting the deadline/inactivity: -100 XP
> * If a user is removed by a team member: -50 XP
> 
> Or should I cover commands for admins like:

No the admin can unassign using the GitHub UI. Please try and keep this codebase as simple as possible. 

I think that the rewards shouldn't be subjective as that is affected by factors that have little to do with the work, like if the collaborator had a good rest, or a good day, or ate a good meal just before reviews etc.

**Comment by Keyrxng** [comment]
> "database" (JSON storage in the repository)

Is this a replacement KV for action-only plugins sort of thing or worker types should have the same sort of storage?

Until AA is finalized we'll be funding wallets with the faucet so unless the permit generation flow is modified to fund their address we'll need to either:

- update the current flow to call the faucet worker before generating and cache
- create a funding plugin to run just before the permit generation plugin and cache
- create a "database" for `/start|stop` and we can balance check them when they `/start`, fund if needed, cache and never fund them again.

listed in order of preference

<hr/>

I'm a fan of this vision as I'm in good standing with this approach lmao but it is the most provable metric to go by especially if XP is always <= dollars earned.

> or ate a good meal just before reviews etc.

Great advice I need to embody more myself 😂

**Comment by 0x4007** [comment]
> > "database" (JSON storage in the repository)
> 
> 
> 
> Is this a replacement KV for action-only plugins sort of thing or worker types should have the same sort of storage?
> 
> 

My proposal https://github.com/ubiquibot/plugin-template/issues/2

> 
> Until AA is finalized we'll be funding wallets with the faucet so unless the permit generation flow is modified to fund their address we'll need to either:
> 
> 

How about sponsored transactions as a first starting point instead? Is this possible?

> 
> - update the current flow to call the faucet worker before generating and cache
> 

I do like that this approach can work on any network, not just gnosis chain. However I assume it's more work to set up. 


> > or ate a good meal just before reviews etc.
> 
> 
> 
> Great advice I need to embody more myself 😂

It's a pretty common negotiation tactic to make an ask over food

**Comment by Keyrxng** [comment]
> How about sponsored transactions as a first starting point instead? Is this possible?

More info [here](https://github.com/ubiquity/safe.ubq.fi/pull/1#issuecomment-2208736409) but yes it's possible I'm sure. Right now we have a fresh EOA with funding, we could just as easily deploy a Safe right now and use that safe as the user wallet and not the EOA. Then setup the infrastructure needed for it.

> However I assume it's more work to set up.

On the OpenZeppelin Defender side it's a couple click process to clone a relayer onto another chain. The faucet needs refactored to handle multiple chains and multiple relayers but it needs refactored anyway to support the first iteration of AA anyway.
